### ISSUE TITLE
Use letsencrypt free certs to not get unsecured warning

### ISSUE THREAD

**Issue by kvarga** [jakebasile/ssltunnel#1]
http://goroutines.com/ssl

**Comment by jakebasile** [comment]
Good idea, but the domain name(s) specified with `-hosts` need to be externally visible for this to work as Let's Encrypt has to verify them by looking for a specific response from that domain. It might be interesting to add it as an option but at that point you should just use the letsencrypt client.

**Comment by kvarga** [comment]
You can just make it under localhost. Avoids SSL warning

On Saturday, January 30, 2016, Jake Basile notifications@github.com wrote:

> Good idea, but the domain name(s) specified with `-hosts` need to be
> externally visible for this to work as Let's Encrypt has to verify them by
> looking for a specific response from that domain. It might be interesting
> to add it as an option but at that point you should just use the
> [letsencrypt client](https://github.com/letsencrypt/letsencrypt).
> 
> On Sat, Jan 30, 2016 at 9:32 AM Kyle Varga <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > http://goroutines.com/ssl
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/jakebasile/ssltunnel/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jakebasile/ssltunnel/issues/1#issuecomment-177260410.

## 

## 

Kyle Varga

**Comment by jakebasile** [comment]
What I mean is that letsencrypt needs to verify your domain from their servers. They can't verify that      localhost means your machine because localhost isn't defined by DNS, so it can't access your system.

An idea would be to add the generated self-signed cert to your local trust store, but that's both kind of creepy and a little out of scope I think.
